set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -gq utf8 on
set -gq status-utf8 on
set -g mouse on

# Stay in copy mode after selecting
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-no-clear

# Double click selects word and doesn't vanish
bind -T copy-mode DoubleClick1Pane select-pane \; send-keys -X select-word
bind -n DoubleClick1Pane select-pane \; copy-mode -M \; send-keys -X select-word

# Use vi or emacs keys in copy mode (pick one)
setw -g mode-keys vi
